### ISSUE TITLE
Update Parallel Cluster Demo to include the UI

### ISSUE THREAD

**Issue by kyleoconnell** [STRIDES/NIHCloudLabAWS#23]

**Comment by kyleoconnell-NIH** [comment]
https://docs.aws.amazon.com/parallelcluster/latest/ug/install-pcui-v3.html

Update: 
https://github.com/STRIDES/NIHCloudLabAWS/blob/main/docs/Install_AWSParallelCluster.md

**Comment by dchesterNIH** [comment]
when trying to install the Parrallel cluster UI via cloud formation stack provided in the link https://docs.aws.amazon.com/parallelcluster/latest/ug/install-pcui-v3.html, the stack attempts to create resources within AWS that are being denied. I have reached out to AWS cloud team in strides to investigate alternatives.

**Comment by dchesterNIH** [comment]
ticket has been submitted with AWS CIT
