### ISSUE TITLE
CREATE AWS Code Buddy Tutorial

### ISSUE THREAD

**Issue by kyleoconnell** [STRIDES/NIHCloudLabAWS#24]

**Comment by kyleoconnell-NIH** [comment]
Can we use code buddy in cloud lab? If so how is it done?

**Comment by dchesterNIH** [comment]
https://aws.amazon.com/codewhisperer/resources/#Getting_started/

AWS Code Whisperer has a full setup page, the setup was pretty easy from their documentation and then from there it would assist users with development. What type of tutorial are you looking for?
