### ISSUE TITLE
Unable to retrieve publicly available dataset in tutorials

### ISSUE THREAD

**Issue by aditipate** [STRIDES/NIHCloudLabAWS#52]
Hello,
I'm currently going through some of the tutorials, and I've encountered an issue when trying to download required datasets. These datasets have been noted to be publicly available within the tutorials, however, I'm unable to download them. I'm specifically having issues with these:  

- **RNA-Seq MyCo tutorial**
  - In Step 2 ( Copy FASTQ Files) six sample reads are being downloaded from a Google Storage Bucket. The tutorial mentions the bucket has been made publicly available but I'm unable to download the read data and instead see an error message **"<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist.</Message></Error>"** within the fastq files. Is the  google storage bucket/data still publicly available or was the location of data changed? 

- **Spleen Segmentation using NVIDIA Models and MONAI tutorial** 
  - I'm able to download public data set from resource = "https://msd-for-monai.s3-us-west-2.amazonaws.com/Task09_Spleen.tar. However, later on I'm unable to download the pretrained model from NVIDIA and instead get an error message **HTTPError: 400 Client Error: Bad Request for url**. The model is also not found on their website (using links provided in READMe). Is the model no longer publicly available or has the link been changed? 
  
Any help or instructions are appreciated, thank you!

**Comment by kyleoconnell-NIH** [comment]
@zbyosufzai  can you please investigate these issues?

**Comment by zbyosufzai** [comment]
Hello,

For RNA-Seq can you try changing the address for the data to **https://storage.googleapis.com/nigms-sandbox/me-inbre-rnaseq-pipelinev2/data/raw_fastqSub/SRR13349122_1.fastq** (e.g., curl https://storage.googleapis.com/nigms-sandbox/me-inbre-rnaseq-pipelinev2/data/raw_fastqSub/SRR13349122_1.fastq --output data/raw_fastq/SRR13349122_1.fastq)? 

For the Spleen Segmentation tutorial it seems that the model name has changed try replacing the model name to **monai_spleen_ct_segmentation** and the version to **0.5.3** , like so:

mmar = {
    Keys.ID: "monai_spleen_ct_segmentation_0.5.3",
    Keys.NAME: "monai_spleen_ct_segmentation",
    Keys.FILE_TYPE: "zip",
    Keys.HASH_TYPE: "md5",
    Keys.HASH_VAL: None,
    Keys.MODEL_FILE: os.path.join("models", "model.pt"),
    Keys.CONFIG_FILE: os.path.join("config", "train.json"),
    Keys.VERSION: '0.5.3'
}

Please let us know if this works for you!

**Comment by zbyosufzai** [comment]
Closing due to issue resolved
